name: marcasom
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^1.0.3
  curved_navigation_bar: ^1.0.3
  page_transition: ^2.0.4
  http: ^0.13.3
  flutter_typeahead: ^4.0.0
  intl: 0.19.0
  flutter_masked_text2: ^0.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
